var nome = "Giovane Costa";
var n1 = "37";
var n2 = "10";
var frase = "Japão é o melhor time do mundo";
//alert(nome + " tem " + idade + " anos.");
//alert(idade + idade2);
console.log(nome);
//console.log(idade + idade2);
console.log(frase.toLowerCase());
console.log(frase.replace("Japão", "Brasil"));
console.log(n1 * n2);
